post http://localhost:8080/todo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiVG9udGluZSBHMTAwIiwic3ViIjoiYjA4YTFiZTAtM2U2ZS00MmIwLTlkNWYtZWU1MzYxZTQ1YjAxIiwiZXhwIjoxNzgyMTY0NTk1LCJpYXQiOjE3ODIwNzgxOTV9.e1wtX7Qs6tc6aEIwGNmnbY2gSb8DLi-98is9GzefF8c

{
    "description": "30 aout 2000."
}

###
get http://localhost:8080/todos/d339ae87-3c6c-439c-8907-f3a592a47452
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiVG9udGluZSBHMTAwIiwic3ViIjoiYjA4YTFiZTAtM2U2ZS00MmIwLTlkNWYtZWU1MzYxZTQ1YjAxIiwiZXhwIjoxNzgyMTY0NTk1LCJpYXQiOjE3ODIwNzgxOTV9.e1wtX7Qs6tc6aEIwGNmnbY2gSb8DLi-98is9GzefF8c

###
get http://localhost:8080/todos?page=1&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiVG9udGluZSBHMTAwIiwic3ViIjoiYjA4YTFiZTAtM2U2ZS00MmIwLTlkNWYtZWU1MzYxZTQ1YjAxIiwiZXhwIjoxNzgyMzM3ODE1LCJpYXQiOjE3ODIyNTE0MTV9.3FnrH9yrok04vpXdMdNNdmSNT2rJzpEZygo0Ks5bFr4

###
delete http://localhost:8080/todos/d1ac5ac6-4c0c-477b-9211-5b1f4e6eccd3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiVG9udGluZSBHMTAwIiwic3ViIjoiYjA4YTFiZTAtM2U2ZS00MmIwLTlkNWYtZWU1MzYxZTQ1YjAxIiwiZXhwIjoxNzgyMTY0NTk1LCJpYXQiOjE3ODIwNzgxOTV9.e1wtX7Qs6tc6aEIwGNmnbY2gSb8DLi-98is9GzefF8c

###
patch http://localhost:8080/todos/a6b6830b-5724-4965-88bf-d8837642baa0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiVG9udGluZSBHMTAwIiwic3ViIjoiYjA4YTFiZTAtM2U2ZS00MmIwLTlkNWYtZWU1MzYxZTQ1YjAxIiwiZXhwIjoxNzgyMTY0NTk1LCJpYXQiOjE3ODIwNzgxOTV9.e1wtX7Qs6tc6aEIwGNmnbY2gSb8DLi-98is9GzefF8c

{
    "description": "30 aout 2024.",
    "is_done": false
}