post http://localhost:8080/todo

{
    "description": "8 mai 1995."
}

###
get http://localhost:8080/todos/b620e4b0-03bb-41f9-a2e3-5fef94f5e14f

###
get http://localhost:8080/todos

###
delete http://localhost:8080/todos/6f3a9668-7efc-4df6-91a8-9506ddf67d98