
post http://localhost:8080/register

{
    "email": "yannemoutsiga@gmail.com",
    "username": "Tontine G05",
    "password": "Vc4yr3af1"
}

###
get http://localhost:8080/me

###
patch http://localhost:8080/user/b08a1be0-3e6e-42b0-9d5f-ee5361e45b01

{
    "username": "Tontine G100"
    //"email": "yannewilfriedm@gmail.com"
}